### ISSUE TITLE
XSOAR Web Editor cursor in the incorrect location

### ISSUE THREAD

**Issue by icholy** [demisto/content#18795]
The integrated web editor (ace) shows the cursor in the incorrect position when editing.

![image](https://user-images.githubusercontent.com/943597/165567705-a4d1d25f-6092-42a6-8ad8-afcd0490752e.png)

Based on some cursory searches, it appears to be related to the fonts used. I have tried disabling all extensions to rule out any potential interference.

* https://stackoverflow.com/questions/15183031/ace-editor-cursor-behaves-incorrectly
* https://groups.google.com/g/ace-discuss/c/Uzpw-VexsDE
* https://github.com/ajaxorg/ace/issues/2548

## Environment

**OS:** Ubuntu 20.04
**Browser:** Chrome Version 101.0.4951.41 (Official Build) (64-bit)

## Update

Adding the following css via [Style Bot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en) let me work around the issue.

``` css
.ace_editor, .ace_editor *{
  font-family: "Monaco", "Menlo", "Ubuntu Mono", "Droid Sans Mono", "Consolas", monospace !important;
}
```
