### ISSUE TITLE
[CommonServerPython] CommandResults: return always strings (regression from return_outputs)

### ISSUE THREAD

**Issue by nicolas-rdgs** [demisto/content#25753]
- The `return_outputs` is now a deprecated function,
- XSOAR recommands to use the combination of `return_results` and `CommandResults` instead,
-  **Issue**: this change broke somes conditionnals tasks, and the results of conditionnals are wrongs.

To illustrate and to reproduce easily the behavior, I have created a test integration and a test playbook that you will find below :

<details>
  <summary><strong>Integration</strong>: test_integration.yml</summary>  

  ### Code
  ```yaml
  commonfields:
  id: test_integration
  version: -1
vcShouldKeepItemLegacyProdMachine: false
name: test_integration
display: test_integration
category: Utilities
image: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAF8ElEQVRo3tVaa2wUVRQ+lUeolLZQHwQxEUIi/GgpakvTst2d7fax7RaEUFOIRW2x7e7cme220BawNSQ1MQZFgYaH8gvlFVAxUYIIJPxRA7FSLCpBJMYnL5FEyh8cvzttodvd6e527izpJCezO3Pn3Pvde853zzkzRKKPAmUOScp+Kg/MoVF7FCiZJLHz5JA1nL8jlzxzxLoklgw908iBc5xBZKPTSzqIAcmvPU3Ltk+NSc/S5vGUz9YASBd0XIXOb2jpKm+cQDAnOvw9CAQXm1ej0ubj9PW5yVHpaXplLJU3bKN83xA9+F+gtJAnkGAdCIm50dm1EBADYgeYrJrDlF0d2UTscj7ZfXcMdN2kJW2PWwPCIZdC/jYEESwHATopwsquHVZHgb9IPAinvhI3owTRJ5L8ITm8xisjye8N+7xLtQk2JyUHPnElJhB3CcB7hCpff9TATI8bPmfzXUCfqeJAuPyzoPinEYEYkMKGr8jtnztkhbmZ3gr1MYiTXaPFgWKRFDuenMpBUyD0wemsBGqVt2EVWmgRmMoh3wjTthdAdlGpP120cz8EO/7FNJBQswm95mR7qKTBoujAqUzADJ4QDiREWDe5lInWbn5FgWysyiEAOmNgDuZFkt+N107+AGw3hUrU6VSsLsTvo4LBHMFEJVDcD7syBh1vEQikFz5SRPflkNRU2PY5cebF/oBPLjM/sMWBVEShKpRuJxeLjsMdyibx/sL2UUXHCNmrtiUZ9n/0bhSaW3uL1A2RuVxiqy1ismvQvR7ycKxx1GuUP0hRdo1GLVvfjsK8NlpMzRdhbowKlSmRQVSumg/kt4csr0Y5dZepyvuEMXh/Ctr1kA1t56vDC28jmaLnbkQZ9VSoJhqxzzh08rmhguyXPqI9xxINzOotPsDkhbXavMZlWmZgeVjh93gbHYx5//kWYFZQkfLg0P2hAg3+M3xwQb1GFe0nacVaDz3XOB3m9xiU5UP64i/M9rzG5dq+6xnanqsZ2u4rc4OEX+P3eBt9ZYQRgnf/4IAwERe7IsyARnl1PBTX9IRKYteD7mNwfNb5gD+4nKG9/9fcIOHX+D3eRggQbp42Pp616wYBUVeaVtwPhM8+H/iuPzODhF/j94QB4RNaFviR1h1K6wPxYkcyZvqHUQckC2y6utN3bzWatzDKqtZGHZDcuh56oWNSH4h3dqRRSdP5frsfXUAkVn1vNTxyO+V5zfG6GGe/ohMIn1BOKFJEej5NBfKEwfHRAWE0OBL6ldh+0H4ussRpOqVXrfFQRdtJneqN+7qD+G9J8N7hbkzEalRBusynrDFuiE7lzbCbK990s6s/Ns732WGkweMMQgxs95JSB0BnzPF61CHKWVC+cY1rZWAG5fmuhs1Vlq96JprsbzLyZRmoL1gaADrZGxHHsiSwKagwwUtDLmV9rBEwKiasvb9sY0FezgIRx/BsUybCoN5Bz32G2CppZLlJTfNssrO94sEoG6MrCLIytN8KS/EB/CQBNS1WCflNIJgeOHvKfcrLlULd2YT5ibwZ5zHxB+JAicbBjgg1MV5KcjcuIk/TdFBrKnwzTsCcyk6LmIynBd04f0Lu1qctNi05CZ2dtbxkKiknyNmQaA0Il5qOTkLDmZyXrQDzMyRNLACPmgmlu+Ebt0MTG991Yhs6sUM34n6nvufYTfsMJ4G9VMjGigNR0+LRbTf84P4lW31wWdOtZlCx8qUpMPw9fZEyUxyI1rYpCA8uGQ5Kkr8I+5y39RFa4Ds8QiCXwVpZYk2q1C9FeIexw/BZm5yMmY01PbgBJ7egcF3oLxnWjl1Kc4Ty6USAPRBDSbTYGpZqacMGJf8TvnqBxEaS8yLqyKpJhnyqfzRgHPrzzzQsfIWweE0CuHw12euHMpVG5f7N+Nwiuh2Yf77hbj6mf84Rap6/YoO1x2cnL3m1Dp2e0h1RwtkuB5CSxhZGPL9zKj4UONX/NncAxEWS/E/FOcaSJ+mfHDlNhNFlrTP0l5x9weL38LF0GrWHq2m2/uLGpT4pWvX/zRDqQjZWrVoAAAAASUVORK5CYII=
configuration: []
script:
  script: |
    register_module_line("test_integration", "start", __line__())

    def fake_action(output):
        table = []
        headers = []

        context = {
            "Result": table,
            "Headers": headers,
            "Action": "test-commandresults",
        }
        if output:
            table = [
                {"action": "test", "step": "1"},
                {"action": "test", "step": "2"}
            ]
            headers = ["action", "test"]

            context["Result"] = table
            context["Headers"] = headers

            return CommandResults(
                outputs_key_field="TestIntegration",
                outputs=context,
                raw_response=table
            )
        else:
            return CommandResults(
                outputs_key_field="TestIntegration",
                outputs=context,
                raw_response=table
            )

    def main():
        command = demisto.command()

        if command == "test-module":
            return return_results("ok")

        elif command == "test-commandresults":
            args = demisto.args()
            output = args.get("output")

            if output == "legacy":
                table = []
                headers = []

                context = {
                    "Result": table,
                    "Headers": headers,
                    "Action": "test-commandresults",
                }

                entry_context = {
                    "TestIntegration(val.Query && val.Query === obj.Query)": {
                        "TestIntegration": context
                    }
                }

                human_readable = tableToMarkdown(name="Action result:", t=table, headers=headers, removeNull=True)

                return return_outputs(
                    human_readable,     #readable_output
                    entry_context,      #outputs
                    table               #raw_response
                )
            else:
                output = argToBoolean(output)

            return return_results(
               fake_action(output)
            )

        else:
            return_error("Unknown Command")


    if __name__ in ("__main__", "__builtin__", "builtins"):
        main()

    register_module_line("test_integration", "end", __line__())
  type: python
  commands:
  - name: test-commandresults
    arguments:
    - name: output
      auto: PREDEFINED
      predefined:
      - "true"
      - "false"
      - legacy
      defaultValue: "false"
  dockerimage: demisto/python3:3.10.10.50695
  runonce: false
  subtype: python3
  ```
</details>

<details>
  <summary><strong>Playbook</strong>: Test-CommandResults.yml</summary>

  ### Code
  ```yml
id: 630f84ee-3e34-4fae-8f35-14f22434652e
version: 4
vcShouldKeepItemLegacyProdMachine: false
name: Test-CommandResults
tags:
- debug
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 20c1a6aa-cfca-4d3c-861f-32526fe706ac
    type: start
    task:
      id: 20c1a6aa-cfca-4d3c-861f-32526fe706ac
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 43025948-cca9-4e19-8e3d-186b5a186a66
    type: regular
    task:
      id: 43025948-cca9-4e19-8e3d-186b5a186a66
      version: -1
      name: Test CommandResults
      script: '|||test-commandresults'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      extend-context:
        simple: result=
      ignore-outputs:
        simple: "true"
      output:
        simple: "false"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 48851fe0-5c4e-4a48-8540-8025aa82d636
    type: condition
    task:
      id: 48851fe0-5c4e-4a48-8540-8025aa82d636
      version: -1
      name: Result is defined?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: result
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 405
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 87a57bd7-687e-4f5e-88b0-b5372a5c724d
    type: regular
    task:
      id: 87a57bd7-687e-4f5e-88b0-b5372a5c724d
      version: -1
      name: Print ok
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: ok
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 200,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 8c58c049-e746-483d-81aa-40333eea01d4
    type: title
    task:
      id: 8c58c049-e746-483d-81aa-40333eea01d4
      version: -1
      name: Close investigation
      description: Prints an error entry with a given message
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 720,
          "y": 665
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 695,
        "width": 900,
        "x": 200,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
  ```
</details>

Basically, the playbook run the custom `test-commandresults` command which has 3 options: 
- true : return CommandResults with a result => it is ok
- false : return CommandResults with a empty list => **not ok** <<<
- legacy : return return_outputs with a empty list => it is ok

For the test, I voluntarily use the extended-context to simplify the context output with the key name `result`.

### Test 1: return a empty list with `return_outputs` (legacy mode) and test if the output result key **is defined**

arg to legacy

![image](https://user-images.githubusercontent.com/10984315/230590560-44a8b135-2753-426a-8c92-bd818268d352.png)

### Test 2: return the same output but with return_results()+CommandResults()

arg to false

![image](https://user-images.githubusercontent.com/10984315/230590637-2dba1e9a-7efc-4e86-8594-9a78ec664d91.png)

### Why?

After a quickly code review, the instancied class CommandResults is passed to return_results() function which pass the context dict to demistomock.py:results() function, that use always `json.dumps()`. So typically, the python None value is converted to "null" string, always.

https://github.com/demisto/content/blob/master/Tests/demistomock/demistomock.py#L631

But I don't know why on the server side, the dict is not loaded by json.loads(), thinking that the "ContentsFormat" is not well used because return_outputs() also uses demisto.results().

When the contents isn't None/not empty, json.loads() is called because all values are casted. So, the behavior changes when the dict or list is empty, json.loads() isn't called in this case.

### Discussion

We have demonstrate this behavior to the Palo Alto Support and they don't see this as a bug, while we do. Their answer was to say that the use of CommandResults was not mandatory, so what is the other way to generate an output in the context without using return_outputs?

In fact, say that "null" string value is defined is true, not false. So the playbook runs well, it is the data that is not correct.

What do you think?
